# Generated by Django 4.2.5 on 2023-09-24 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(default="None", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("biography", models.TextField(default="None")),
                ("birthday", models.DateField(default=datetime.date(2023, 9, 24))),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published", models.DateField(default=datetime.date(2023, 9, 24))),
                ("category", models.CharField(default="category", max_length=200)),
                ("show_count", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_blog_app.author",
                    ),
                ),
            ],
        ),
    ]
