# Generated by Django 4.2.5 on 2023-10-03 14:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base_blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
        migrations.AlterField(
            model_name="author",
            name="birthday",
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "is_published",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base_blog_app.article",
                    ),
                ),
            ],
        ),
    ]
