# Generated by Django 4.2.5 on 2023-10-06 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_blog_app", "0005_alter_comment_article_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="published",
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
        migrations.AlterField(
            model_name="author",
            name="birthday",
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
    ]
