# Generated by Django 4.2.5 on 2023-09-24 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EagleTails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cur_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("res", models.CharField(max_length=20)),
            ],
        ),
    ]
