# Generated by Django 4.2.5 on 2023-10-03 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("online_store_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="reg_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_ordered",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
