# Generated by Django 4.2.5 on 2023-10-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "online_store_app",
            "0002_alter_client_reg_date_alter_order_date_ordered_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
