# Generated by Django 4.2.5 on 2023-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("online_store_app", "0003_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="./media/"),
        ),
    ]
